spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dataRestExample
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    rest:
      detection-strategy: annotated
      return-body-on-create: true
      return-body-on-update: true
      base-path: api
server:
  port: 8090
